warehouse:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ikb44942.us-east-1

      # User/password auth
      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: accountadmin
      database: northwind
      warehouse: compute_wh
      schema: raw
      threads: 12
      client_session_keep_alive: False